apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-ooo"
  description: "A cool quarkus app"
  annotations:
    argocd/app-name: my-quarkus-app-ooo-dev
    backstage.io/kubernetes-id: my-quarkus-app-ooo
    backstage.io/kubernetes-namespace: my-quarkus-app-ooo-dev
    janus-idp.io/tekton-enabled : 'true'
    backstage.io/source-location: url:https://github.com/slallemand/my-quarkus-app-ooo
    backstage.io/techdocs-ref: url:https://github.com/slallemand/my-quarkus-app-ooo
    gitlab.com/project-slug: slallemand/my-quarkus-app-ooo
    quay.io/repository-slug: "/my-quarkus-app-ooo"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-jr597.sandbox426.opentlc.com/#https://github.com/slallemand/my-quarkus-app-ooo?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-jr597.sandbox426.opentlc.com/#https://github.com/slallemand/my-quarkus-app-ooo?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "dev-user"
  providesApis:
    - "my-quarkus-app-ooo"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app-ooo"
  description: "A cool quarkus app"
spec:
  type: openapi
  lifecycle: production
  owner: "dev-user"
  definition:
    $text: ./openapi.yaml